import { useMemo, useState } from 'react'
import { CalendarPlus, Check, Circle, Clock3 } from 'lucide-react'
import { useApp } from '../../context/AppContext'
import { addDays, formatDayLong, formatDayShort, formatDueCountdown, formatTimeRange, isSameDay, startOfDay } from '../../lib/date'
import type { CalendarEvent } from '../../types'
import Button from '../ui/Button'; import Chip from '../ui/Chip'; import s from '../views.module.css'

function EventRow({event,risk}:{event:CalendarEvent;risk:boolean}){return <div className={`${s.event} ${event.kind==='work-session'?s.eventWork:''} ${risk?s.eventRisk:''}`}><span className={s.time}>{formatTimeRange(event.start,event.end)}</span><div><strong>{event.title}</strong><small>{event.kind==='work-session'?'Focus session · placed around your calendar':'Google Calendar'}</small></div>{event.kind==='work-session'&&<Chip tone={risk?'risk':'default'}>{risk?'Tight buffer':'On track'}</Chip>}</div>}

export default function Dashboard({view}:{view:'today'|'week'|'assignments'}){
 const app=useApp(); const [showAdd,setShowAdd]=useState(false); const [title,setTitle]=useState('Study group'); const [day,setDay]=useState(()=>new Date().toISOString().slice(0,10)); const [start,setStart]=useState('17:00'); const [end,setEnd]=useState('18:00')
 const allEvents=useMemo(()=>[...app.personalEvents,...app.schedule.workSessions].sort((a,b)=>+new Date(a.start)-+new Date(b.start)),[app.personalEvents,app.schedule.workSessions]);
 const today=allEvents.filter(e=>isSameDay(new Date(e.start),app.now)); const pending=app.assignments.filter(a=>a.status!=='done').sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt));
 const add=()=>{const st=new Date(`${day}T${start}`),en=new Date(`${day}T${end}`);if(title&&en>st){app.addPersonalEvent({title,start:st.toISOString(),end:en.toISOString()});setShowAdd(false)}}
 const header=<header className={s.pageHeader}><div><h1 className={s.display}>{view==='today'?`Good ${app.now.getHours()<12?'morning':app.now.getHours()<17?'afternoon':'evening'}, ${app.studentName}.`:view==='week'?'Your week, already worked out.':'Every assignment, one clear plan.'}</h1><p>{view==='today'?formatDayLong(app.now):view==='week'?'Homework is fitted around school, sleep, and your calendar.':`${pending.length} active assignments from Google Classroom.`}</p></div><div className={s.toolbar}><span className={s.status}><i className={s.statusDot}/>Calendar synced</span>{view!=='assignments'&&<Button size="sm" onClick={()=>setShowAdd(v=>!v)}><CalendarPlus size={16}/>Add event</Button>}</div></header>
 if(view==='week') return <main className={s.page}>{header}{showAdd&&<AddEvent {...{title,setTitle,day,setDay,start,setStart,end,setEnd,add}}/>}<div className={s.week}>{Array.from({length:7},(_,i)=>addDays(startOfDay(app.now),i)).map(d=><section className={s.day} key={d.toISOString()}><h3>{formatDayShort(d)}</h3>{allEvents.filter(e=>isSameDay(new Date(e.start),d)).map(e=><div className={`${s.miniEvent} ${e.kind==='work-session'?s.miniWork:''}`} key={e.id}><span className={s.time}>{formatTimeRange(e.start,e.end)}</span><br/><strong>{e.title}</strong></div>)}</section>)}</div></main>
 if(view==='assignments') return <main className={s.page}>{header}<section className={s.section}><div className={s.assignmentList}>{app.assignments.sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)).map(a=>{const c=app.classes.find(x=>x.id===a.classId);const risk=app.schedule.atRisk.has(a.id);return <article className={s.assignment} key={a.id}><div><div className={s.assignmentTitle}>{a.title}</div><div className={s.meta}><span>{c?.name}</span><span>·</span><span className={s.time}>{formatDueCountdown(a.dueAt,app.now)}</span><span>·</span><span>{a.estimatedMinutes} min planned</span></div><div className={s.progress}><span style={{width:a.status==='done'?'100%':a.status==='in-progress'?'45%':'8%'}}/></div></div><button aria-label={`Mark ${a.title} complete`} onClick={()=>app.setAssignmentStatus(a.id,a.status==='done'?'not-started':'done')}>{a.status==='done'?<Check color="var(--color-blue-strong)"/>:<Circle color={risk?'var(--color-alert-strong)':'var(--color-ink-muted)'}/>}</button></article>})}</div></section></main>
 return <main className={s.page}>{header}{showAdd&&<AddEvent {...{title,setTitle,day,setDay,start,setStart,end,setEnd,add}}/>}<div className={s.layout}><section className={s.section}><div className={s.sectionTitle}><h2>Today’s plan</h2><Chip>{today.length} blocks</Chip></div>{today.length?<div className={s.timeline}>{today.map(e=><EventRow key={e.id} event={e} risk={!!e.assignmentId&&app.schedule.atRisk.has(e.assignmentId)}/>)}</div>:<div className={s.empty}>You’re clear today. Your next focus block will appear here.</div>}</section><aside className={s.section}><div className={s.sectionTitle}><h2>Coming up</h2><Clock3 size={20}/></div><div className={s.assignmentList}>{pending.slice(0,5).map(a=><article className={s.assignment} key={a.id}><div><div className={s.assignmentTitle}>{a.title}</div><div className={s.meta}><span>{app.classes.find(c=>c.id===a.classId)?.name}</span><span className={s.time}>{formatDueCountdown(a.dueAt,app.now)}</span></div></div>{app.schedule.atRisk.has(a.id)&&<Chip tone="risk">At risk</Chip>}</article>)}</div></aside></div></main>
}

function AddEvent(p:{title:string;setTitle:(v:string)=>void;day:string;setDay:(v:string)=>void;start:string;setStart:(v:string)=>void;end:string;setEnd:(v:string)=>void;add:()=>void}){return <section className={s.section} style={{marginBottom:24}}><div className={s.sectionTitle}><h2>Add calendar event</h2><span className={s.muted}>Your schedule replans instantly</span></div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr auto',gap:10}}><input className={s.input} value={p.title} onChange={e=>p.setTitle(e.target.value)} placeholder="Event name"/><input className={s.input} type="date" value={p.day} onChange={e=>p.setDay(e.target.value)}/><input className={s.input} type="time" value={p.start} onChange={e=>p.setStart(e.target.value)}/><input className={s.input} type="time" value={p.end} onChange={e=>p.setEnd(e.target.value)}/><Button onClick={p.add}>Add</Button></div></section>}
